config/routes.rb
DateTracker::Application.routes.draw do
  resources :important_dates

  root :to => "important_dates#index"

end

app/models/important_date.rb
class ImportantDate < ActiveRecord::Base
  attr_accessible :date, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/important_dates_controller.rb
class ImportantDatesController < ApplicationController
  # GET /important_dates
  # GET /important_dates.json
  def index
    @important_dates = ImportantDate.where('date >= ?', Date.today).order("date")

    respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @important_dates }
    end
  end

  # GET /important_dates/1
  # GET /important_dates/1.json
  def show
    @important_date = ImportantDate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @important_date }
    end
  end

  # GET /important_dates/new
  # GET /important_dates/new.json
  def new
    @important_date = ImportantDate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @important_date }
    end
  end

  # GET /important_dates/1/edit
  def edit
    @important_date = ImportantDate.find(params[:id])
  end

  # POST /important_dates
  # POST /important_dates.json
  def create
    @important_date = ImportantDate.new(params[:important_date])

    respond_to do |format|
      if @important_date.save
        format.html { redirect_to @important_date, notice: 'Important date was successfully created.' }
        format.json { render json: @important_date, status: :created, location: @important_date }
      else
        format.html { render action: "new" }
        format.json { render json: @important_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /important_dates/1
  # PUT /important_dates/1.json
  def update
    @important_date = ImportantDate.find(params[:id])

    respond_to do |format|
      if @important_date.update_attributes(params[:important_date])
        format.html { redirect_to @important_date, notice: 'Important date was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @important_date.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /important_dates/1
  # DELETE /important_dates/1.json
  def destroy
    @important_date = ImportantDate.find(params[:id])
    @important_date.destroy

    respond_to do |format|
      format.html { redirect_to important_dates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/important_dates_helper.rb
module ImportantDatesHelper
end

app/views/important_dates/_form.html.erb
<%= form_for(@important_date) do |f| %>
  <% if @important_date.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@important_date.errors.count, "error") %> prohibited this important_date from being saved:</h2>

      <ul>
      <% @important_date.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/important_dates/edit.html.erb
<h1>Editing important_date</h1>

<%= render 'form' %>

<%= link_to 'Show', @important_date %> |
<%= link_to 'Back', important_dates_path %>

app/views/important_dates/index.html.erb
<h1>Important Dates of the Future</h1>
<h2>Predicted by tea leaves and some dried up parsley</h2>

<table>
  <tr>
    <th>Date</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @important_dates.each do |important_date| %>
  <tr>
    <td><%= important_date.date %></td>
    <td><%= important_date.name %></td>
    <td><%= link_to 'Show', important_date %></td>
    <td><%= link_to 'Edit', edit_important_date_path(important_date) %></td>
    <td><%= link_to 'Destroy', important_date, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Important date', new_important_date_path %>

app/views/important_dates/new.html.erb
<h1>New important_date</h1>

<%= render 'form' %>

<%= link_to 'Back', important_dates_path %>

app/views/important_dates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @important_date.date %>
</p>

<p>
  <b>Name:</b>
  <%= @important_date.name %>
</p>


<%= link_to 'Edit', edit_important_date_path(@important_date) %> |
<%= link_to 'Back', important_dates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DateTracker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>